export const PREDEFINED_OCCASIONS = [
  { name: "New Year's Day", emoji: '🎉', primary: '#BE185D', secondary: '#F59E0B', background: '#FFF1F2' },
  { name: 'Makar Sankranti / Pongal', emoji: '🌾', primary: '#D97706', secondary: '#059669', background: '#FEF3C7' },
  { name: 'Republic Day', emoji: '🇮🇳', primary: '#1E40AF', secondary: '#D97706', background: '#EFF6FF' },
  { name: 'Rose Day ❤️🌹', emoji: '🌹', primary: '#E11D48', secondary: '#FB7185', background: '#FFF1F2' },
  { name: 'Propose Day 💍', emoji: '💍', primary: '#7C3AED', secondary: '#C084FC', background: '#F5F3FF' },
  { name: 'Chocolate Day 🍫', emoji: '🍫', primary: '#7C2D12', secondary: '#D97706', background: '#FFFBEB' },
  { name: 'Teddy Day 🧸', emoji: '🧸', primary: '#B45309', secondary: '#FBBF24', background: '#FEF3C7' },
  { name: 'Promise Day 🤝', emoji: '🤝', primary: '#0284C7', secondary: '#38BDF8', background: '#F0F9FF' },
  { name: 'Hug Day 🤗', emoji: '🤗', primary: '#EA580C', secondary: '#F97316', background: '#FFF7ED' },
  { name: 'Kiss Day 💋', emoji: '💋', primary: '#BE123C', secondary: '#F43F5E', background: '#FFF1F2' },
  { name: "Valentine's Day ❤️", emoji: '❤️', primary: '#991B1B', secondary: '#F43F5E', background: '#FFF1F2' },
  { name: 'Holi', emoji: '🎨', primary: '#C026D3', secondary: '#EAB308', background: '#FDF4FF' },
  { name: 'Ugadi', emoji: '🌿', primary: '#15803D', secondary: '#84CC16', background: '#F0FDF4' },
  { name: 'Ramzan Eid', emoji: '🌙', primary: '#047857', secondary: '#F59E0B', background: '#ECFDF5' },
  { name: "Mother's Day ❤️", emoji: '❤️', primary: '#DB2777', secondary: '#F472B6', background: '#FDF2F8' },
  { name: 'Eid-ul-Adha / Bakrid', emoji: '🌙', primary: '#065F46', secondary: '#10B981', background: '#ECFDF5' },
  { name: "Father's Day ❤️", emoji: '❤️', primary: '#1E3A8A', secondary: '#60A5FA', background: '#EFF6FF' },
  { name: 'Friendship Day', emoji: '👭', primary: '#D97706', secondary: '#FBBF24', background: '#FEF3C7' },
  { name: 'Independence Day', emoji: '🇮🇳', primary: '#C2410C', secondary: '#15803D', background: '#FFF7ED' },
  { name: 'Raksha Bandhan / Rakhi', emoji: '🪢', primary: '#B91C1C', secondary: '#F59E0B', background: '#FEF2F2' },
  { name: "Teachers' Day 👨‍🏫", emoji: '👨‍🏫', primary: '#4338CA', secondary: '#818CF8', background: '#EEF2FF' },
  { name: 'Ganesh Chaturthi / Vinayaka Chavithi 🐘', emoji: '🐘', primary: '#C2410C', secondary: '#EAB308', background: '#FFF7ED' },
  { name: 'Diwali / Deepavali 🪔', emoji: '🪔', primary: '#B45309', secondary: '#F59E0B', background: '#FFFBEB' },
  { name: "Children's Day 👧👦", emoji: '👧👦', primary: '#0D9488', secondary: '#2DD4BF', background: '#F0FDFA' },
  { name: 'Christmas Day 🎄🎅', emoji: '🎄', primary: '#991B1B', secondary: '#15803D', background: '#FEF2F2' },
  { name: "Women's Day 👩", emoji: '👩', primary: '#9D174D', secondary: '#F472B6', background: '#FDF2F8' },
  { name: "Grandparents' Day 👴👵", emoji: '👴👵', primary: '#92400E', secondary: '#D97706', background: '#FEF3C7' },
];
